name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  lint-and-build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: 'npm'
      - name: Setup Biome
        uses: biomejs/setup-biome@v2.6.0
        with: 
          version: 2.1.4
      - name: Run Biome check
        run: npx biome ci
      - run: npm ci
      - name: Build Nuxt app
        run: npm run build --if-present
